[package]
name = "voxelize-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
voxelize = "0.8.31"
actix-web = "4.2.1"
specs = "0.18.0"